# Generated by Django 4.1.6 on 2023-02-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="service", to="panel.product"
            ),
        ),
    ]
