# Generated by Django 4.1.6 on 2023-02-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0003_ingredient_remove_service_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="duration",
            field=models.DurationField(null=True),
        ),
    ]
