# Generated by Django 4.1.6 on 2023-02-13 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0004_product_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="panel.ingredient"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="panel.product",
            ),
        ),
    ]
