# Generated by Django 4.1.6 on 2023-02-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0007_alter_product_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
