# Generated by Django 4.1.4 on 2023-02-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='files',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
