# Generated by Django 4.1.4 on 2023-02-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_rename_files_service_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='images',
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads')),
                ('my_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='panel.service')),
            ],
        ),
    ]
